export const teamMembers = [
    {
        id:1,
        name: "Pallavi Agrawal",
        role: "CEO & Founder",
        image: "/img/all-img/team-1.png",
        description: "We craft visually engaging, user-friendly websites that blend design precision with seamless functionality.",
        social: {
            linkedin: "https://www.linkedin.com/in/pallavijainagrawal/",
            instagram: "https://www.instagram.com/pallavi_0586/",
            // github: "#",
        },
    },
    {
        id:2,
        name: "Rutvik Patel",
        role: "COO-Chief Operating Officer",
        image: "/img/all-img/team-2.png",
        description: "We combine creativity and expertise to craft seamless, user-centric digital experiences. Focusing on clean code, scalable solutions, and intuitive designs that drive your business forward.",
        social: {
            linkedin: "https://www.linkedin.com/in/pallavijainagrawal/",
            instagram: "#",
            // github: "#",
        },
    },
    // {
    //     id:3,
    //     name: "Shreya Sharma",
    //     role: "HR Executive",
    //     image: "/img/all-img/team-3.png",
    //     description: "We design intuitive, user-centered interfaces that deliver smooth, engaging, and accessible digital experiences.",
    //     social: {
    //         facebook: "#",
    //         instagram: "#",
    //         github: "#",
    //     },
    // },
    // {
    //     id:4,
    //     name: "Swati Jain",
    //     role: "CEO’s Office Associate",
    //     image: "/img/all-img/team-4.png",
    //     description: "We create captivating 2D and 3D animations that bring stories, characters, and interfaces to life with fluid motion and visual impact.",
    //     social: {
    //         facebook: "#",
    //         instagram: "#",
    //         github: "#",
    //     },
    // },
    // {
    //     id:5,
    //     name: "Arjun Gupta",
    //     role: "Associate Salesforce consultant",
    //     image: "/img/all-img/team-5.png",
    //     description: "We use fresh ideas, close collaboration, and technical skill to build engaging, easy-to-play games.Our goal is to deliver smooth, immersive experiences that players love.",
    //     social: {
    //         facebook: "#",
    //         instagram: "#",
    //         github: "#",
    //     },
    // },
    // {
    //     id:6,
    //     name: "Priya Bhingradiya",
    //     role: "Salesforce Developer",
    //     image: "/img/all-img/team-6.png",
    //     description: "We apply strong engineering principles, creative thinking, and clean code to build reliable, high-performance software solutions.",
    //     social: {
    //         facebook: "#",
    //         instagram: "#",
    //         github: "#",
    //     },
    // },
    // {
    //     id:7,
    //     name: "Priya Bhingradiya",
    //     role: "Salesforce Developer",
    //     image: "/img/all-img/team-6.png",
    //     description: "We apply strong engineering principles, creative thinking, and clean code to build reliable, high-performance software solutions.",
    //     social: {
    //         facebook: "#",
    //         instagram: "#",
    //         github: "#",
    //     },
    // },
    // {
    //     id:8,
    //     name: "Priya Bhingradiya",
    //     role: "Salesforce Developer",
    //     image: "/img/all-img/team-6.png",
    //     description: "We apply strong engineering principles, creative thinking, and clean code to build reliable, high-performance software solutions.",
    //     social: {
    //         facebook: "#",
    //         instagram: "#",
    //         github: "#",
    //     },
    // },
    // {
    //     id:9,
    //     name: "Priya Bhingradiya",
    //     role: "Salesforce Developer",
    //     image: "/img/all-img/team-6.png",
    //     description: "We apply strong engineering principles, creative thinking, and clean code to build reliable, high-performance software solutions.",
    //     social: {
    //         facebook: "#",
    //         instagram: "#",
    //         github: "#",
    //     },
    // },
];